### ISSUE TITLE
数据集在哪里可以下载？

### ISSUE THREAD

**Issue by zzwei1** [chencodeX/Global-AI-Challenge-on-Meteorology#1]
你好，我最近在看雷达回波外推的工作。请问这个’IEEE ICDM 2018 全球气象AI挑战赛‘的数据集在哪里还可以下载呢？官网的我试了一下，已经结束了比赛，下载不了。

**Comment by chencodeX** [comment]
这个数据量还挺大的，大约50GB。你确定？

**Comment by zzwei1** [comment]
> 这个数据量还挺大的，大约50GB。你确定？

emm,您那里方便传上来吗。我还挺想试试的。

**Comment by chencodeX** [comment]
我周末传到百度云试试

**Comment by zzwei1** [comment]
> 我周末传到百度云试试

好的好的，多谢多谢！

**Comment by chencodeX** [comment]
链接: https://pan.baidu.com/s/1bKkTbPfpjH8KwS_TCSDxMA  密码: sk3o
这是test数据，你先试试看

**Comment by chencodeX** [comment]
链接: https://pan.baidu.com/s/18e91hPrBqHq8id0vvifkvg  密码: 190v
其中一个训练集

**Comment by chencodeX** [comment]
链接: https://pan.baidu.com/s/14pY5LGY3RsLDKxhPl_afRQ  密码: 8qlp

**Comment by bixinduanle** [comment]
> 链接: https://pan.baidu.com/s/14pY5LGY3RsLDKxhPl_afRQ 密码: 8qlp

太感谢了！

**Comment by studyhardstudyhard** [comment]
官方说有32万组数据，哪位大神可以上传一下

**Comment by chencodeX** [comment]
> 官方说有32万组数据，哪位大神可以上传一下

百度网盘不能用了吗

**Comment by studyhardstudyhard** [comment]
> > 官方说有32万组数据，哪位大神可以上传一下
> 
> 百度网盘不能用了吗

上面百度网盘下载后，有2万的数据，我看官网上说有32万，还有其他组数据吗

**Comment by GFZShiwai** [comment]
非常感谢您的分享，请问您是将官方所有的训练数据都上传了吗

**Comment by chencodeX** [comment]
忘了已经，可以下载看看文件数量，应该不是全部的，因为后面决赛我没有参加
